name: Tests
on: push

jobs:
  # <---------------- TEST BASIC CONFIG ------------------>
  code-quality-basic:
    name: Basic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check out self as repo
        uses: actions/checkout@v2
        with:
          repository: erzz/codeclimate-standalone
          ref: ${{ github.ref }}
          path: ./.github/actions/self
      - name: Basic Test
        uses: ./.github/actions/self
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Basic Reports
          path: |
            codeclimate-report.json
            codeclimate-report.html
  # <--------------- TEST ADVANCED CONFIG ---------------->
  code-quality-advanced:
    name: Advanced
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check out self as repo
        uses: actions/checkout@v2
        with:
          repository: erzz/codeclimate-standalone
          ref: ${{ github.ref }}
          path: ./.github/actions/self
      - name: Advanced Test
        uses: ./.github/actions/self
        with:
          html_report: true
          info_threshold: 10
          minor_threshold: 5
          major_threshold: 1
          critical_threshold: 0
          blocker_threshold: 0
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Advanced Reports
          path: |
            codeclimate-report.json
            codeclimate-report.html
